import { z } from 'genkit';
export declare const ClothingSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    imageUri: z.ZodOptional<z.ZodString>;
    category: z.ZodOptional<z.ZodString>;
    color: z.ZodOptional<z.ZodString>;
    style: z.ZodOptional<z.ZodString>;
    confidence: z.ZodOptional<z.ZodNumber>;
    cleanedImage: z.ZodOptional<z.ZodString>;
    isBackgroundRemoved: z.ZodOptional<z.ZodBoolean>;
    fabric: z.ZodOptional<z.ZodString>;
    texture: z.ZodOptional<z.ZodString>;
    silhouette: z.ZodOptional<z.ZodString>;
    materialType: z.ZodOptional<z.ZodString>;
    hasPattern: z.ZodOptional<z.ZodBoolean>;
    patternDescription: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id?: string | undefined;
    imageUri?: string | undefined;
    category?: string | undefined;
    color?: string | undefined;
    style?: string | undefined;
    confidence?: number | undefined;
    cleanedImage?: string | undefined;
    isBackgroundRemoved?: boolean | undefined;
    fabric?: string | undefined;
    texture?: string | undefined;
    silhouette?: string | undefined;
    materialType?: string | undefined;
    hasPattern?: boolean | undefined;
    patternDescription?: string | undefined;
}, {
    id?: string | undefined;
    imageUri?: string | undefined;
    category?: string | undefined;
    color?: string | undefined;
    style?: string | undefined;
    confidence?: number | undefined;
    cleanedImage?: string | undefined;
    isBackgroundRemoved?: boolean | undefined;
    fabric?: string | undefined;
    texture?: string | undefined;
    silhouette?: string | undefined;
    materialType?: string | undefined;
    hasPattern?: boolean | undefined;
    patternDescription?: string | undefined;
}>;
export declare const processClothing: import("@genkit-ai/core/lib/action-Dt9i8CGd").u<z.ZodAny, z.ZodAny, z.ZodTypeAny, import("@genkit-ai/core/lib/action-Dt9i8CGd").q<z.ZodTypeAny>>;
export declare const OutfitSuggestionSchema: z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    reason: z.ZodString;
    items: z.ZodArray<z.ZodString, "many">;
    generatedImageUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    title: string;
    description: string;
    reason: string;
    items: string[];
    generatedImageUrl?: string | undefined;
}, {
    title: string;
    description: string;
    reason: string;
    items: string[];
    generatedImageUrl?: string | undefined;
}>;
export declare const generateOutfitImage: import("@genkit-ai/core/lib/action-Dt9i8CGd").u<z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    imageUri: z.ZodOptional<z.ZodString>;
    category: z.ZodOptional<z.ZodString>;
    color: z.ZodOptional<z.ZodString>;
    style: z.ZodOptional<z.ZodString>;
    confidence: z.ZodOptional<z.ZodNumber>;
    cleanedImage: z.ZodOptional<z.ZodString>;
    isBackgroundRemoved: z.ZodOptional<z.ZodBoolean>;
    fabric: z.ZodOptional<z.ZodString>;
    texture: z.ZodOptional<z.ZodString>;
    silhouette: z.ZodOptional<z.ZodString>;
    materialType: z.ZodOptional<z.ZodString>;
    hasPattern: z.ZodOptional<z.ZodBoolean>;
    patternDescription: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id?: string | undefined;
    imageUri?: string | undefined;
    category?: string | undefined;
    color?: string | undefined;
    style?: string | undefined;
    confidence?: number | undefined;
    cleanedImage?: string | undefined;
    isBackgroundRemoved?: boolean | undefined;
    fabric?: string | undefined;
    texture?: string | undefined;
    silhouette?: string | undefined;
    materialType?: string | undefined;
    hasPattern?: boolean | undefined;
    patternDescription?: string | undefined;
}, {
    id?: string | undefined;
    imageUri?: string | undefined;
    category?: string | undefined;
    color?: string | undefined;
    style?: string | undefined;
    confidence?: number | undefined;
    cleanedImage?: string | undefined;
    isBackgroundRemoved?: boolean | undefined;
    fabric?: string | undefined;
    texture?: string | undefined;
    silhouette?: string | undefined;
    materialType?: string | undefined;
    hasPattern?: boolean | undefined;
    patternDescription?: string | undefined;
}>, "many">, z.ZodString, z.ZodTypeAny, import("@genkit-ai/core/lib/action-Dt9i8CGd").q<z.ZodTypeAny>>;
export declare const generateOutfits: import("@genkit-ai/core/lib/action-Dt9i8CGd").u<z.ZodObject<{
    wardrobe: z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        imageUri: z.ZodOptional<z.ZodString>;
        category: z.ZodOptional<z.ZodString>;
        color: z.ZodOptional<z.ZodString>;
        style: z.ZodOptional<z.ZodString>;
        confidence: z.ZodOptional<z.ZodNumber>;
        cleanedImage: z.ZodOptional<z.ZodString>;
        isBackgroundRemoved: z.ZodOptional<z.ZodBoolean>;
        fabric: z.ZodOptional<z.ZodString>;
        texture: z.ZodOptional<z.ZodString>;
        silhouette: z.ZodOptional<z.ZodString>;
        materialType: z.ZodOptional<z.ZodString>;
        hasPattern: z.ZodOptional<z.ZodBoolean>;
        patternDescription: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        id?: string | undefined;
        imageUri?: string | undefined;
        category?: string | undefined;
        color?: string | undefined;
        style?: string | undefined;
        confidence?: number | undefined;
        cleanedImage?: string | undefined;
        isBackgroundRemoved?: boolean | undefined;
        fabric?: string | undefined;
        texture?: string | undefined;
        silhouette?: string | undefined;
        materialType?: string | undefined;
        hasPattern?: boolean | undefined;
        patternDescription?: string | undefined;
    }, {
        id?: string | undefined;
        imageUri?: string | undefined;
        category?: string | undefined;
        color?: string | undefined;
        style?: string | undefined;
        confidence?: number | undefined;
        cleanedImage?: string | undefined;
        isBackgroundRemoved?: boolean | undefined;
        fabric?: string | undefined;
        texture?: string | undefined;
        silhouette?: string | undefined;
        materialType?: string | undefined;
        hasPattern?: boolean | undefined;
        patternDescription?: string | undefined;
    }>, "many">;
    numSuggestions: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    event: z.ZodOptional<z.ZodString>;
    referenceItemId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    wardrobe: {
        id?: string | undefined;
        imageUri?: string | undefined;
        category?: string | undefined;
        color?: string | undefined;
        style?: string | undefined;
        confidence?: number | undefined;
        cleanedImage?: string | undefined;
        isBackgroundRemoved?: boolean | undefined;
        fabric?: string | undefined;
        texture?: string | undefined;
        silhouette?: string | undefined;
        materialType?: string | undefined;
        hasPattern?: boolean | undefined;
        patternDescription?: string | undefined;
    }[];
    numSuggestions: number;
    event?: string | undefined;
    referenceItemId?: string | undefined;
}, {
    wardrobe: {
        id?: string | undefined;
        imageUri?: string | undefined;
        category?: string | undefined;
        color?: string | undefined;
        style?: string | undefined;
        confidence?: number | undefined;
        cleanedImage?: string | undefined;
        isBackgroundRemoved?: boolean | undefined;
        fabric?: string | undefined;
        texture?: string | undefined;
        silhouette?: string | undefined;
        materialType?: string | undefined;
        hasPattern?: boolean | undefined;
        patternDescription?: string | undefined;
    }[];
    numSuggestions?: number | undefined;
    event?: string | undefined;
    referenceItemId?: string | undefined;
}>, z.ZodArray<z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    reason: z.ZodString;
    items: z.ZodArray<z.ZodString, "many">;
    generatedImageUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    title: string;
    description: string;
    reason: string;
    items: string[];
    generatedImageUrl?: string | undefined;
}, {
    title: string;
    description: string;
    reason: string;
    items: string[];
    generatedImageUrl?: string | undefined;
}>, "many">, z.ZodTypeAny, import("@genkit-ai/core/lib/action-Dt9i8CGd").q<z.ZodTypeAny>>;
