import { z } from 'genkit';
export declare const ClothingSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    imageUri: z.ZodOptional<z.ZodString>;
    category: z.ZodString;
    color: z.ZodString;
    style: z.ZodString;
    confidence: z.ZodNumber;
    cleanedImage: z.ZodOptional<z.ZodString>;
    isBackgroundRemoved: z.ZodBoolean;
    material: z.ZodOptional<z.ZodString>;
    fabric: z.ZodOptional<z.ZodString>;
    pattern: z.ZodOptional<z.ZodString>;
    texture: z.ZodOptional<z.ZodString>;
    silhouette: z.ZodOptional<z.ZodString>;
    materialType: z.ZodOptional<z.ZodString>;
    hasPattern: z.ZodOptional<z.ZodBoolean>;
    patternDescription: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    category: string;
    color: string;
    style: string;
    confidence: number;
    isBackgroundRemoved: boolean;
    id?: string | undefined;
    imageUri?: string | undefined;
    cleanedImage?: string | undefined;
    material?: string | undefined;
    fabric?: string | undefined;
    pattern?: string | undefined;
    texture?: string | undefined;
    silhouette?: string | undefined;
    materialType?: string | undefined;
    hasPattern?: boolean | undefined;
    patternDescription?: string | undefined;
}, {
    category: string;
    color: string;
    style: string;
    confidence: number;
    isBackgroundRemoved: boolean;
    id?: string | undefined;
    imageUri?: string | undefined;
    cleanedImage?: string | undefined;
    material?: string | undefined;
    fabric?: string | undefined;
    pattern?: string | undefined;
    texture?: string | undefined;
    silhouette?: string | undefined;
    materialType?: string | undefined;
    hasPattern?: boolean | undefined;
    patternDescription?: string | undefined;
}>;
export declare const ai: import("genkit/lib/index-5yfMIzsW").G;
